#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/victoromorogbe/development/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/victoromorogbe/Documents/pally"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "FLUTTER_CLI_BUILD_MODE=release"
export "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuMzYuMC0wLjUucHJl,RkxVVFRFUl9DSEFOTkVMPWJldGE=,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049NmM3OTQ4NDIxMA==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049NTZmNjRjMjY0Nw==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMC4wIChidWlsZCAzLjEwLjAtNzUuMS5iZXRhKQ=="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=false"
export "TREE_SHAKE_ICONS=true"
export "PACKAGE_CONFIG=/Users/victoromorogbe/Documents/pally/.dart_tool/package_config.json"
